package com.atlasops.documents.application;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.atlasops.documents.domain.AllowedContentType;
import com.atlasops.documents.domain.Document;
import com.atlasops.documents.domain.ports.DocumentRepository;
import com.atlasops.documents.domain.ports.ObjectStoragePort;
import com.atlasops.shared.domain.ports.Clock;
import com.atlasops.shared.domain.types.TenantId;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.Optional;
import java.util.regex.Pattern;
import net.jqwik.api.*;

/**
 * Validates: Requirements 10.5 Property 16: MinIO Storage Path Format
 *
 * <p>Requirement 10.5: THE Document_Module SHALL store documents in MinIO using the path pattern:
 * {tenantId}/{year}/{month}/{documentId}/{filename} where filename is limited to 255 characters and
 * restricted to alphanumeric characters, hyphens, underscores, and dots.
 *
 * <p>Tests the InitiateUploadUseCase path generation behavior.
 */
@Tag("Feature:project-implementation-kickoff")
@Tag("Property-16:MinIO-Storage-Path-Format")
class InitiateUploadStoragePathPropertyTest {

  private static final String VALID_CHECKSUM = "a".repeat(64);
  private static final String PRESIGNED_URL = "https://minio.local/bucket/presigned-url";

  /**
   * Full path pattern: {tenantId}/{year}/{month}/{documentId}/{filename} - tenantId: alphanumeric,
   * hyphens, underscores - year: exactly 4 digits - month: exactly 2 digits (01-12) - documentId:
   * alphanumeric, hyphens, underscores - filename: alphanumeric, hyphens, underscores, dots (1-255
   * chars)
   */
  private static final Pattern FULL_PATH_PATTERN =
      Pattern.compile("^[a-zA-Z0-9_-]+/\\d{4}/\\d{2}/[a-zA-Z0-9_-]+/[a-zA-Z0-9._-]+$");

  /**
   * Property: For ANY valid combination of tenantId, documentId, filename and timestamp, the
   * storage path generated by InitiateUploadUseCase ALWAYS follows the format
   * {tenantId}/{year}/{month}/{documentId}/{filename}.
   */
  @Property(tries = 100)
  void should_alwaysProduceValidPathFormat_forAnyValidInputs(
      @ForAll("validTenantIds") String tenantId,
      @ForAll("validDocumentIds") String documentId,
      @ForAll("validFilenames") String filename,
      @ForAll("validTimestamps") Instant timestamp) {

    InitiateUploadResult result = executeUseCase(tenantId, documentId, filename, timestamp);

    assertThat(result.storagePath()).matches(FULL_PATH_PATTERN);
  }

  /**
   * Property: For ANY valid inputs, the storage path ALWAYS contains exactly 4 forward slashes
   * separating exactly 5 path segments.
   */
  @Property(tries = 100)
  void should_alwaysHaveFiveSegmentsSeparatedBySlashes_forAnyValidInputs(
      @ForAll("validTenantIds") String tenantId,
      @ForAll("validDocumentIds") String documentId,
      @ForAll("validFilenames") String filename,
      @ForAll("validTimestamps") Instant timestamp) {

    InitiateUploadResult result = executeUseCase(tenantId, documentId, filename, timestamp);

    String[] segments = result.storagePath().split("/");
    assertThat(segments).hasSize(5);
    assertThat(segments[0]).isEqualTo(tenantId);
    assertThat(segments[3]).isEqualTo(documentId);
    assertThat(segments[4]).isEqualTo(filename);
  }

  /**
   * Property: For ANY valid timestamp, the year segment is ALWAYS 4 digits and the month segment is
   * ALWAYS 2 digits (zero-padded) matching the UTC date.
   */
  @Property(tries = 100)
  void should_alwaysHave4DigitYearAnd2DigitMonth_forAnyValidTimestamp(
      @ForAll("validTenantIds") String tenantId,
      @ForAll("validDocumentIds") String documentId,
      @ForAll("validFilenames") String filename,
      @ForAll("validTimestamps") Instant timestamp) {

    InitiateUploadResult result = executeUseCase(tenantId, documentId, filename, timestamp);
    String[] segments = result.storagePath().split("/");

    LocalDate expectedDate = timestamp.atZone(ZoneOffset.UTC).toLocalDate();
    String expectedYear = String.valueOf(expectedDate.getYear());
    String expectedMonth = String.format("%02d", expectedDate.getMonthValue());

    // Year is 4 digits
    assertThat(segments[1]).hasSize(4);
    assertThat(segments[1]).isEqualTo(expectedYear);

    // Month is zero-padded 2 digits
    assertThat(segments[2]).hasSize(2);
    assertThat(segments[2]).isEqualTo(expectedMonth);

    int monthValue = Integer.parseInt(segments[2]);
    assertThat(monthValue).isBetween(1, 12);
  }

  /**
   * Property: For ANY valid filename (up to 255 chars, restricted to alphanumeric, hyphens,
   * underscores, dots), the generated path correctly includes the full filename unchanged.
   */
  @Property(tries = 100)
  void should_alwaysPreserveFilenameUnchanged_forAnyValidFilename(
      @ForAll("validTenantIds") String tenantId,
      @ForAll("validDocumentIds") String documentId,
      @ForAll("validFilenames") String filename,
      @ForAll("validTimestamps") Instant timestamp) {

    InitiateUploadResult result = executeUseCase(tenantId, documentId, filename, timestamp);
    String[] segments = result.storagePath().split("/");

    assertThat(segments[4]).isEqualTo(filename);
    assertThat(segments[4].length()).isLessThanOrEqualTo(255);
    assertThat(segments[4]).matches("^[a-zA-Z0-9._-]+$");
  }

  // ---- Helper to execute InitiateUploadUseCase with mocked dependencies ----

  private InitiateUploadResult executeUseCase(
      String tenantId, String documentId, String filename, Instant timestamp) {

    DocumentRepository documentRepository = mock(DocumentRepository.class);
    ObjectStoragePort objectStoragePort = mock(ObjectStoragePort.class);
    Clock clock = mock(Clock.class);

    Document document =
        Document.create(
            documentId,
            new TenantId(tenantId),
            null,
            filename,
            AllowedContentType.PDF,
            1024L,
            VALID_CHECKSUM,
            timestamp);

    when(documentRepository.findById(documentId, tenantId)).thenReturn(Optional.of(document));
    when(clock.now()).thenReturn(timestamp);
    lenient()
        .when(objectStoragePort.generatePresignedUploadUrl(anyString(), anyString(), anyInt()))
        .thenReturn(PRESIGNED_URL);

    InitiateUploadUseCase useCase =
        new InitiateUploadUseCase(documentRepository, objectStoragePort, clock);
    InitiateUploadCommand command = new InitiateUploadCommand(documentId, tenantId);

    return useCase.execute(command);
  }

  // ---- Custom Arbitraries ----

  @Provide
  Arbitrary<String> validTenantIds() {
    return Arbitraries.strings()
        .withChars(
            'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
            'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7',
            '8', '9', '-', '_')
        .ofMinLength(3)
        .ofMaxLength(30)
        .filter(s -> s.matches("^[a-zA-Z0-9_-]+$") && !s.isBlank());
  }

  @Provide
  Arbitrary<String> validDocumentIds() {
    return Arbitraries.strings()
        .withChars(
            'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
            'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7',
            '8', '9', '-', '_')
        .ofMinLength(3)
        .ofMaxLength(36)
        .filter(s -> s.matches("^[a-zA-Z0-9_-]+$") && !s.isBlank());
  }

  @Provide
  Arbitrary<String> validFilenames() {
    // Generate filenames: alphanumeric, hyphens, underscores, dots; 1-255 chars
    // We generate a base name and append an extension to ensure realistic filenames
    Arbitrary<String> baseName =
        Arbitraries.strings()
            .withChars(
                'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
                'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y',
                'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '-', '_')
            .ofMinLength(1)
            .ofMaxLength(245);

    Arbitrary<String> extension = Arbitraries.of(".pdf", ".docx", ".png", ".jpeg", ".txt", ".doc");

    return Combinators.combine(baseName, extension)
        .as((base, ext) -> base + ext)
        .filter(f -> f.length() >= 1 && f.length() <= 255)
        .filter(f -> f.matches("^[a-zA-Z0-9._-]+$"));
  }

  @Provide
  Arbitrary<Instant> validTimestamps() {
    // Range covering multiple years and all months: 2020-01-01 to 2030-12-31
    long minEpoch = Instant.parse("2020-01-01T00:00:00Z").getEpochSecond();
    long maxEpoch = Instant.parse("2030-12-31T23:59:59Z").getEpochSecond();
    return Arbitraries.longs().between(minEpoch, maxEpoch).map(Instant::ofEpochSecond);
  }
}
