package com.atlasops.boot;

import java.util.UUID;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;

/**
 * Test configuration providing TEST_RUN_ID isolation for integration tests.
 *
 * <p>The TEST_RUN_ID pattern ensures that each test run uses a unique prefix for
 * Redis keys and tenant IDs, preventing cross-test data contamination when multiple
 * test suites run in parallel (e.g., in CI or with multiple developers).
 *
 * <p>Usage in integration tests:
 * <pre>{@code
 * @SpringBootTest
 * @Import(TestRunConfig.class)
 * class SomeIntegrationTest {
 *
 *   @Autowired
 *   String testRunId;
 *
 *   @Autowired
 *   String isolatedRedisPrefix;
 * }
 * }</pre>
 *
 * <p>Validates: P1.25 — Test Isolation Infrastructure (TEST_RUN_ID)
 */
@TestConfiguration
public class TestRunConfig {

    /**
     * Generates a short, unique identifier for this test run (8 hex chars).
     * Used as a namespace prefix to isolate Redis keys, tenant IDs, and
     * other shared resources from parallel test runs.
     *
     * @return 8-character hex string derived from a random UUID
     */
    @Bean
    public String testRunId() {
        return UUID.randomUUID().toString().replace("-", "").substring(0, 8);
    }

    /**
     * Provides an isolated Redis key prefix scoped to this test run.
     * All Redis operations during this test run should use this prefix
     * to avoid interfering with other parallel test runs.
     *
     * @param testRunId the unique test run ID generated by {@link #testRunId()}
     * @return a Redis prefix string like {@code "test:a1b2c3d4:"}
     */
    @Bean
    public String isolatedRedisPrefix(String testRunId) {
        return "test:" + testRunId + ":";
    }
}
