package com.atlasops.boot.integration;

import static org.assertj.core.api.Assertions.assertThat;

import com.atlasops.activities.infrastructure.SpringDataActivityRepository;
import com.atlasops.ai.infrastructure.PgVectorSearchAdapter;
import com.atlasops.ai.infrastructure.SpringDataAIAnalysisRecordRepository;
import com.atlasops.ai.infrastructure.SpringDataGoldenDatasetRepository;
import com.atlasops.ai.infrastructure.SpringDataPromptVersionRepository;
import com.atlasops.approvals.infrastructure.SpringDataApprovalLedgerRepository;
import com.atlasops.approvals.infrastructure.SpringDataApprovalRepository;
import com.atlasops.audit.infrastructure.SpringDataAuditEntryRepository;
import com.atlasops.auth.application.ValidateTokenUseCase;
import com.atlasops.auth.domain.ports.AccountLockoutPort;
import com.atlasops.auth.domain.ports.AuthUserPort;
import com.atlasops.auth.domain.ports.JwtTokenPort;
import com.atlasops.auth.domain.ports.PasswordHashPort;
import com.atlasops.auth.domain.ports.RefreshTokenRepository;
import com.atlasops.customers.domain.ports.CustomerRepository;
import com.atlasops.customers.infrastructure.SpringDataCustomerRepository;
import com.atlasops.customers.infrastructure.SpringDataUserCustomerAssociationRepository;
import com.atlasops.documents.domain.ports.DocumentRepository;
import com.atlasops.documents.infrastructure.SpringDataDocumentRepository;
import com.atlasops.imports.application.StartImportUseCase;
import com.atlasops.imports.domain.ports.ImportPort;
import com.atlasops.notifications.domain.ports.EmailSenderPort;
import com.atlasops.notifications.domain.ports.NotificationPreferencesRepository;
import com.atlasops.notifications.domain.ports.NotificationRepository;
import com.atlasops.notifications.infrastructure.SpringDataNotificationPreferencesRepository;
import com.atlasops.notifications.infrastructure.SpringDataNotificationRepository;
import com.atlasops.operations.domain.ports.JobRepository;
import com.atlasops.operations.infrastructure.SpringDataJobRepository;
import com.atlasops.requests.domain.ports.ServiceRequestRepository;
import com.atlasops.requests.infrastructure.SpringDataCommentRepository;
import com.atlasops.requests.infrastructure.SpringDataRequestStatusHistoryRepository;
import com.atlasops.requests.infrastructure.SpringDataServiceRequestRepository;
import com.atlasops.search.infrastructure.SpringDataSearchIndexRepository;
import com.atlasops.shared.domain.ports.Clock;
import com.atlasops.shared.domain.ports.FeatureFlagPort;
import com.atlasops.shared.domain.ports.IdGenerator;
import com.atlasops.shared.domain.ports.OutboxEventRepository;
import com.atlasops.tenants.domain.ports.TenantRepository;
import com.atlasops.tenants.infrastructure.SpringDataTenantRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.ResponseEntity;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.test.context.ActiveProfiles;
import software.amazon.awssdk.services.s3.S3Client;

/**
 * Exports the live OpenAPI contract generated by SpringDoc during integration tests.
 *
 * <p>The test keeps the contract artifact aligned with the running application by retrieving
 * `/v3/api-docs` from the test application context and writing it to the build directory.
 */
@SpringBootTest(
    webEnvironment = WebEnvironment.RANDOM_PORT,
    properties = {
      "APP_ENV=test",
      "APP_PORT=0",
      "DATABASE_URL=jdbc:h2:mem:atlasops_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL",
      "REDIS_URL=redis://localhost:6379",
      "OBJECT_STORAGE_ENDPOINT=http://localhost:9000",
      "OBJECT_STORAGE_BUCKET=atlasops-test",
      "JWT_ISSUER=atlasops-test",
      "JWT_AUDIENCE=atlasops-api-test",
      "spring.jpa.hibernate.ddl-auto=none",
      "spring.sql.init.mode=never",
      "spring.task.scheduling.enabled=false",
      "spring.cloud.function.scan.enabled=false",
      "spring.cloud.function.autodetect=false",
      "spring.autoconfigure.exclude=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration",
      "LOG_LEVEL=INFO"
    })
@ActiveProfiles({"test", "local"})
@DisplayName("OpenAPI Contract Export")
class OpenApiContractExportIntegrationTest {

  private static final Path OPENAPI_OUTPUT =
      Path.of("build", "reports", "openapi", "openapi.json");

  @Autowired private TestRestTemplate restTemplate;
  private final ObjectMapper objectMapper = new ObjectMapper();
  @MockBean private ValidateTokenUseCase validateTokenUseCase;
  @MockBean private AccountLockoutPort accountLockoutPort;
  @MockBean private AuthUserPort authUserPort;
  @MockBean private JwtTokenPort jwtTokenPort;
  @MockBean private RefreshTokenRepository refreshTokenRepository;
  @MockBean private PasswordHashPort passwordHashPort;
  @MockBean private CustomerRepository customerRepository;
  @MockBean private DocumentRepository documentRepository;
  @MockBean private EmailSenderPort emailSenderPort;
  @MockBean private NotificationPreferencesRepository notificationPreferencesRepository;
  @MockBean private NotificationRepository notificationRepository;
  @MockBean private JobRepository jobRepository;
  @MockBean private ServiceRequestRepository serviceRequestRepository;
  @MockBean private FeatureFlagPort featureFlagPort;
  @MockBean private IdGenerator idGenerator;
  @MockBean private Clock clock;
  @MockBean private TenantRepository tenantRepository;
  @MockBean private ImportPort importPort;
  @MockBean private StartImportUseCase startImportUseCase;
  @MockBean private SpringDataActivityRepository springDataActivityRepository;

  @MockBean(name = "vectorStore")
  private Object vectorStore;

  @MockBean private PgVectorSearchAdapter pgVectorSearchAdapter;
  @MockBean private SpringDataAIAnalysisRecordRepository springDataAIAnalysisRecordRepository;
  @MockBean private SpringDataGoldenDatasetRepository springDataGoldenDatasetRepository;
  @MockBean private SpringDataPromptVersionRepository springDataPromptVersionRepository;
  @MockBean private SpringDataApprovalLedgerRepository springDataApprovalLedgerRepository;
  @MockBean private SpringDataApprovalRepository springDataApprovalRepository;
  @MockBean private SpringDataAuditEntryRepository springDataAuditEntryRepository;
  @MockBean private SpringDataCustomerRepository springDataCustomerRepository;

  @MockBean
  private SpringDataUserCustomerAssociationRepository springDataUserCustomerAssociationRepository;

  @MockBean private SpringDataDocumentRepository springDataDocumentRepository;

  @MockBean
  private SpringDataNotificationPreferencesRepository springDataNotificationPreferencesRepository;

  @MockBean private SpringDataNotificationRepository springDataNotificationRepository;
  @MockBean private SpringDataJobRepository springDataJobRepository;
  @MockBean private SpringDataCommentRepository springDataCommentRepository;

  @MockBean
  private SpringDataRequestStatusHistoryRepository springDataRequestStatusHistoryRepository;

  @MockBean private SpringDataServiceRequestRepository springDataServiceRequestRepository;
  @MockBean private SpringDataSearchIndexRepository springDataSearchIndexRepository;
  @MockBean private SpringDataTenantRepository springDataTenantRepository;
  @MockBean private JavaMailSender javaMailSender;
  @MockBean private S3Client s3Client;
  @MockBean private OutboxEventRepository outboxEventRepository;

  @Test
  @DisplayName("should_exportOpenApiSpec_when_apiDocsAreAvailable")
  void should_exportOpenApiSpec_when_apiDocsAreAvailable() throws IOException {
    ResponseEntity<String> response = restTemplate.getForEntity("/v3/api-docs", String.class);

    assertThat(response.getStatusCode().is2xxSuccessful())
        .as(
            "Expected /v3/api-docs to return 2xx but got %s with body: %s",
            response.getStatusCode(), response.getBody())
        .isTrue();
    assertThat(response.getBody()).isNotNull();

    Files.createDirectories(OPENAPI_OUTPUT.getParent());
    Files.writeString(OPENAPI_OUTPUT, response.getBody());

    assertThat(Files.exists(OPENAPI_OUTPUT)).isTrue();
    assertThat(Files.size(OPENAPI_OUTPUT)).isGreaterThan(0L);
  }

  @Test
  @DisplayName("should_includeCriticalPaths_and_basicSchemas_in_exportedContract")
  void should_includeCriticalPaths_and_basicSchemas_in_exportedContract() throws IOException {
    ResponseEntity<String> response = restTemplate.getForEntity("/v3/api-docs", String.class);

    assertThat(response.getStatusCode().is2xxSuccessful()).isTrue();
    assertThat(response.getBody()).isNotNull();

    Map<String, Object> spec = objectMapper.readValue(response.getBody(), Map.class);
    Map<String, Object> paths = (Map<String, Object>) spec.get("paths");
    Map<String, Object> components = (Map<String, Object>) spec.get("components");
    Map<String, Object> schemas =
        components == null ? Map.of() : (Map<String, Object>) components.get("schemas");

    List<String> criticalPaths =
        List.of(
            "/api/v1/auth/login",
            "/api/v1/tenants",
            "/api/v1/customers",
            "/api/v1/requests",
            "/api/v1/documents",
            "/api/v1/approvals");

    for (String path : criticalPaths) {
      assertThat(paths)
          .as("Expected critical path %s to be present in OpenAPI export", path)
          .containsKey(path);
    }

    assertThat(schemas)
        .as("Expected basic response schemas to be exported")
        .containsKeys(
            "TokenResponse",
            "TenantResponse",
            "CustomerResponse",
            "ServiceRequestResponse",
            "DocumentResponse");
  }

  @Test
  @DisplayName("should_preserveBaselineContractPaths_from_committedOpenApiSnapshot")
  void should_preserveBaselineContractPaths_from_committedOpenApiSnapshot() throws IOException {
    ResponseEntity<String> response = restTemplate.getForEntity("/v3/api-docs", String.class);
    assertThat(response.getStatusCode().is2xxSuccessful()).isTrue();
    assertThat(response.getBody()).isNotNull();

    Map<String, Object> spec = objectMapper.readValue(response.getBody(), Map.class);
    Map<String, Object> paths = (Map<String, Object>) spec.get("paths");

    String baseline = Files.readString(Path.of("src", "main", "resources", "openapi.yaml"));
    Matcher matcher = Pattern.compile("^  (/[^\n:]+):$", Pattern.MULTILINE).matcher(baseline);
    List<String> baselinePaths = new ArrayList<>();
    while (matcher.find()) {
      String path = matcher.group(1);
      if (!"/v3/api-docs".equals(path)) {
        baselinePaths.add(path);
      }
    }

    assertThat(baselinePaths).isNotEmpty();
    for (String path : baselinePaths) {
      assertThat(paths)
          .as("Expected baseline path %s to remain present in the live export", path)
          .containsKey(path);
    }
  }
}
