package com.atlasops.boot.integration;

import static org.assertj.core.api.Assertions.assertThat;

import com.atlasops.auth.application.ValidateTokenUseCase;
import com.atlasops.auth.domain.ports.AccountLockoutPort;
import com.atlasops.auth.domain.ports.AuthUserPort;
import com.atlasops.auth.domain.ports.JwtTokenPort;
import com.atlasops.auth.domain.ports.RefreshTokenRepository;
import com.atlasops.auth.domain.ports.PasswordHashPort;
import com.atlasops.customers.domain.ports.CustomerRepository;
import com.atlasops.documents.domain.ports.DocumentRepository;
import com.atlasops.imports.domain.ports.ImportPort;
import com.atlasops.imports.application.StartImportUseCase;
import com.atlasops.notifications.domain.ports.EmailSenderPort;
import com.atlasops.notifications.domain.ports.NotificationPreferencesRepository;
import com.atlasops.notifications.domain.ports.NotificationRepository;
import com.atlasops.operations.domain.ports.JobRepository;
import com.atlasops.requests.domain.ports.ServiceRequestRepository;
import com.atlasops.shared.domain.ports.Clock;
import com.atlasops.shared.domain.ports.FeatureFlagPort;
import com.atlasops.shared.domain.ports.IdGenerator;
import com.atlasops.shared.domain.ports.OutboxEventRepository;
import com.atlasops.tenants.domain.ports.TenantRepository;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.http.ResponseEntity;
import com.atlasops.activities.infrastructure.SpringDataActivityRepository;
import com.atlasops.ai.infrastructure.SpringDataAIAnalysisRecordRepository;
import com.atlasops.ai.infrastructure.SpringDataGoldenDatasetRepository;
import com.atlasops.ai.infrastructure.SpringDataPromptVersionRepository;
import com.atlasops.ai.infrastructure.PgVectorSearchAdapter;
import com.atlasops.approvals.infrastructure.SpringDataApprovalLedgerRepository;
import com.atlasops.approvals.infrastructure.SpringDataApprovalRepository;
import com.atlasops.audit.infrastructure.SpringDataAuditEntryRepository;
import com.atlasops.customers.infrastructure.SpringDataCustomerRepository;
import com.atlasops.customers.infrastructure.SpringDataUserCustomerAssociationRepository;
import com.atlasops.documents.infrastructure.SpringDataDocumentRepository;
import com.atlasops.notifications.infrastructure.SpringDataNotificationPreferencesRepository;
import com.atlasops.notifications.infrastructure.SpringDataNotificationRepository;
import com.atlasops.operations.infrastructure.SpringDataJobRepository;
import com.atlasops.requests.infrastructure.SpringDataCommentRepository;
import com.atlasops.requests.infrastructure.SpringDataRequestStatusHistoryRepository;
import com.atlasops.requests.infrastructure.SpringDataServiceRequestRepository;
import com.atlasops.search.infrastructure.SpringDataSearchIndexRepository;
import com.atlasops.tenants.infrastructure.SpringDataTenantRepository;
import org.springframework.mail.javamail.JavaMailSender;
import software.amazon.awssdk.services.s3.S3Client;

/**
 * Exports the live OpenAPI contract generated by SpringDoc during integration tests.
 *
 * <p>The test keeps the contract artifact aligned with the running application by retrieving
 * `/v3/api-docs` from the test application context and writing it to the build directory.
 */
@SpringBootTest(
    webEnvironment = WebEnvironment.RANDOM_PORT,
    properties = {
      "APP_ENV=test",
      "APP_PORT=0",
      "DATABASE_URL=jdbc:h2:mem:atlasops_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL",
      "REDIS_URL=redis://localhost:6379",
      "OBJECT_STORAGE_ENDPOINT=http://localhost:9000",
      "OBJECT_STORAGE_BUCKET=atlasops-test",
      "JWT_ISSUER=atlasops-test",
      "JWT_AUDIENCE=atlasops-api-test",
      "spring.jpa.hibernate.ddl-auto=none",
      "spring.sql.init.mode=never",
      "spring.task.scheduling.enabled=false",
      "LOG_LEVEL=INFO"
    })
@ActiveProfiles({"test", "local"})
@DisplayName("OpenAPI Contract Export")
class OpenApiContractExportIntegrationTest {

  private static final Path OPENAPI_OUTPUT =
      Path.of("backend", "app-boot", "build", "reports", "openapi", "openapi.json");

  @Autowired private TestRestTemplate restTemplate;
  @MockBean private ValidateTokenUseCase validateTokenUseCase;
  @MockBean private AccountLockoutPort accountLockoutPort;
  @MockBean private AuthUserPort authUserPort;
  @MockBean private JwtTokenPort jwtTokenPort;
  @MockBean private RefreshTokenRepository refreshTokenRepository;
  @MockBean private PasswordHashPort passwordHashPort;
  @MockBean private CustomerRepository customerRepository;
  @MockBean private DocumentRepository documentRepository;
  @MockBean private EmailSenderPort emailSenderPort;
  @MockBean private NotificationPreferencesRepository notificationPreferencesRepository;
  @MockBean private NotificationRepository notificationRepository;
  @MockBean private JobRepository jobRepository;
  @MockBean private ServiceRequestRepository serviceRequestRepository;
  @MockBean private FeatureFlagPort featureFlagPort;
  @MockBean private IdGenerator idGenerator;
  @MockBean private Clock clock;
  @MockBean private TenantRepository tenantRepository;
  @MockBean private ImportPort importPort;
  @MockBean private StartImportUseCase startImportUseCase;
  @MockBean private SpringDataActivityRepository springDataActivityRepository;
  @MockBean(name = "vectorStore") private Object vectorStore;
  @MockBean private PgVectorSearchAdapter pgVectorSearchAdapter;
  @MockBean private SpringDataAIAnalysisRecordRepository springDataAIAnalysisRecordRepository;
  @MockBean private SpringDataGoldenDatasetRepository springDataGoldenDatasetRepository;
  @MockBean private SpringDataPromptVersionRepository springDataPromptVersionRepository;
  @MockBean private SpringDataApprovalLedgerRepository springDataApprovalLedgerRepository;
  @MockBean private SpringDataApprovalRepository springDataApprovalRepository;
  @MockBean private SpringDataAuditEntryRepository springDataAuditEntryRepository;
  @MockBean private SpringDataCustomerRepository springDataCustomerRepository;
  @MockBean private SpringDataUserCustomerAssociationRepository springDataUserCustomerAssociationRepository;
  @MockBean private SpringDataDocumentRepository springDataDocumentRepository;
  @MockBean private SpringDataNotificationPreferencesRepository springDataNotificationPreferencesRepository;
  @MockBean private SpringDataNotificationRepository springDataNotificationRepository;
  @MockBean private SpringDataJobRepository springDataJobRepository;
  @MockBean private SpringDataCommentRepository springDataCommentRepository;
  @MockBean private SpringDataRequestStatusHistoryRepository springDataRequestStatusHistoryRepository;
  @MockBean private SpringDataServiceRequestRepository springDataServiceRequestRepository;
  @MockBean private SpringDataSearchIndexRepository springDataSearchIndexRepository;
  @MockBean private SpringDataTenantRepository springDataTenantRepository;
  @MockBean private JavaMailSender javaMailSender;
  @MockBean private S3Client s3Client;
  @MockBean private OutboxEventRepository outboxEventRepository;

  @Test
  @DisplayName("should_exportOpenApiSpec_when_apiDocsAreAvailable")
  void should_exportOpenApiSpec_when_apiDocsAreAvailable() throws IOException {
    ResponseEntity<String> response = restTemplate.getForEntity("/v3/api-docs", String.class);

    assertThat(response.getStatusCode().is2xxSuccessful()).isTrue();
    assertThat(response.getBody()).isNotNull();

    Files.createDirectories(OPENAPI_OUTPUT.getParent());
    Files.writeString(OPENAPI_OUTPUT, response.getBody());

    assertThat(Files.exists(OPENAPI_OUTPUT)).isTrue();
    assertThat(Files.size(OPENAPI_OUTPUT)).isGreaterThan(0L);
  }
}
